{
 "title": "Kep Computer Logs V3",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Server", "query": "grafana-postgresql-datasource" },
   {
    "name": "tag",
    "label": "Select Tag",
    "query": {
     "query": "SELECT DISTINCT tag FROM tags ORDER BY tag ASC;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT\r\n  ROUND((total_kb - free_kb) * 100.0 / total_kb, 1) AS \"RAM Used %\"\r\nFROM ram_usage\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT \r\n  usage AS \"CPU %\"\r\nFROM cpu_usage\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Tag Value over time ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT\r\n  source_timestamp AS \"time\",\r\n  tag,\r\n  CAST(value AS DOUBLE PRECISION) AS \"Value\"\r\nFROM tags\r\nWHERE $__timeFilter(server_timestamp)\r\n  AND tag = '${tag}'\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Current Tag value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT\r\n  CAST(value AS DOUBLE PRECISION) AS \"Current Value\"\r\nFROM tags\r\nWHERE tag = '${tag}'\r\nORDER BY server_timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Tag Status Code Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT\r\n  server_timestamp AS \"time\",\r\n  status_code AS \"Status\"\r\nFROM tags\r\nWHERE $__timeFilter(server_timestamp)\r\n  AND tag = '${tag}'\r\nORDER BY 1 ASC;"
    }
   ]
  },
  {
   "title": "Logger Connection Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  CASE WHEN event = 'connected' THEN host_name ELSE 'Disconnected' END AS \"Status\",\r\n  reason\r\nFROM connection_log\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "KepServer OPC Connection Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT\r\n  timestamp,\r\n  client_name,\r\n  kind,\r\n  reason\r\nFROM opc_connection_events \r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "KepServer Event Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT\r\n  timestamp,\r\n  event_name,\r\n  source,\r\n  message\r\nFROM events\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp DESC\r\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Historic Service Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  name,\r\n  status\r\nFROM services\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Current Service Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT DISTINCT ON (name)\r\n  name,\r\n  status,\r\n  service_type,\r\n  timestamp AS \"Last Seen\"\r\nFROM services\r\nORDER BY name, timestamp DESC;"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  usage AS \"CPU %\"\r\nFROM cpu_usage\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Network Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  interface,\r\n  kb_bytes_sent - LAG(kb_bytes_sent) OVER (PARTITION BY interface ORDER BY timestamp) AS \"Sent KB\",\r\n  kb_bytes_received - LAG(kb_bytes_received) OVER (PARTITION BY interface ORDER BY timestamp) AS \"Received KB\"\r\nFROM network_usage\r\nWHERE $__timeFilter(timestamp) \r\n  AND operational_status = 'Up'\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "kepserverlogger",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  ROUND((total_kb - free_kb) * 100.0 / total_kb, 1) AS \"Used %\",\r\n  ROUND(free_kb * 100.0 / total_kb, 1) AS \"Free %\"\r\nFROM ram_usage\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY 1;"
    }
   ]
  }
 ]
}