apiVersion: v1
kind: Service
metadata:
  name: timescaledb-nodeport
  namespace: kepserverlogger
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/part-of: kepserverlogger
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      nodePort: 30432