apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idl

resources:
  - k3s/namespace.yaml
  - k3s/configmap.yaml
  - k3s/timescaledb.yaml
  - k3s/ingestor.yaml

configMapGenerator:
  - name: idl-files
    files:
      - settings.json=settings.json
      - balcones_pcn_tags.csv=tags/balcones_pcn_tags.csv
      - balcones_dmz_tags.csv=tags/balcones_dmz_tags.csv

secretGenerator:
  - name: idl-servers
    files:
      - servers.json=servers.json
