apiVersion: v1
kind: Service
metadata:
  name: timescaledb-nodeport
  namespace: idl
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/part-of: idl
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      nodePort: 30432